# Generated by Django 2.2.3 on 2019-09-01 07:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import helper.validate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0017_auto_20190831_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_setting_key', models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6), helper.validate.validate_key], verbose_name='operation setting ID')),
                ('check_interval_seconds', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='check interval seconds')),
                ('status_valid_seconds', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='status valid seconds')),
                ('latest_version', models.CharField(max_length=200, validators=[helper.validate.validate_version], verbose_name='latest version')),
                ('oldest_version', models.CharField(max_length=200, validators=[helper.validate.validate_version], verbose_name='oldest version')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'operation setting',
                'verbose_name_plural': 'operation setting',
            },
        ),
    ]
