# Generated by Django 2.2.3 on 2019-09-01 04:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import helper.validate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('option', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0017_auto_20190831_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6), helper.validate.validate_key], verbose_name='License ID')),
                ('license_expiration', models.DateTimeField(verbose_name='expiration date')),
                ('activate_expiration', models.DateTimeField(verbose_name='activation date')),
                ('activation_pass', models.CharField(blank=True, max_length=128, validators=[helper.validate.validate_activation_pass], verbose_name='activation pass')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated date')),
                ('start_app_num', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Only input number 0-9')], verbose_name='app start number')),
                ('pause', models.BooleanField(default=False, verbose_name='pause')),
            ],
            options={
                'verbose_name': 'license',
                'verbose_name_plural': 'licenses',
            },
        ),
        migrations.CreateModel(
            name='LicenseOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(verbose_name='purchase date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated date')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license.License', verbose_name='license')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.Option', verbose_name='option')),
            ],
            options={
                'verbose_name': 'license option',
                'verbose_name_plural': 'license options',
            },
        ),
        migrations.AddField(
            model_name='license',
            name='option',
            field=models.ManyToManyField(through='license.LicenseOption', to='option.Option', verbose_name='option'),
        ),
        migrations.AddField(
            model_name='license',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='license',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
