# Generated by Django 2.2.3 on 2019-09-01 07:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import helper.validate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_exe_status_key', models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6), helper.validate.validate_key], verbose_name='app exe status ID')),
                ('start_app_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start app datetime')),
                ('status_last_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='status last update')),
                ('status_code', models.CharField(max_length=5, verbose_name='status code')),
                ('exe_status_expiration', models.DateTimeField(default=django.utils.timezone.now, verbose_name='exe status expiration')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated date')),
                ('activation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activation.Activation', verbose_name='activation')),
            ],
            options={
                'verbose_name': 'execution status',
                'verbose_name_plural': 'execution status',
            },
        ),
    ]
