# Generated by Django 2.2.3 on 2019-08-31 06:15

import django.core.validators
from django.db import migrations, models
import helper.validate


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20190327_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is deleted'),
        ),
        migrations.AddField(
            model_name='product',
            name='overview',
            field=models.TextField(blank=True, verbose_name='Overview'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_key',
            field=models.CharField(default='11ax4q', max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6), helper.validate.validate_key], verbose_name='product ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='product one', max_length=255, verbose_name='product name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_no',
            field=models.CharField(default='product no one', max_length=50, verbose_name='product no'),
            preserve_default=False,
        ),
    ]
