# Generated by Django 2.2.3 on 2019-08-31 04:00

import django.core.validators
from django.db import migrations, models, connection
import django.utils.timezone
import os


def load_data_from_sql(apps, schema_editor):
   file_path = os.path.join(os.path.dirname(__file__), '../sql/zenkoku.sql')
   sql_statement = open(file_path, encoding="utf-8").read()
   with connection.cursor() as c:
       c.execute(sql_statement)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ken_id', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='ken id')),
                ('city_id', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='city id')),
                ('town_id', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)], verbose_name='town id')),
                ('zip', models.CharField(blank=True, max_length=8, null=True, verbose_name='zip')),
                ('office_flg', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='office flg')),
                ('delete_flg', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='delete flg')),
                ('ken_name', models.CharField(blank=True, max_length=8, null=True, verbose_name='ken name')),
                ('ken_furi', models.CharField(blank=True, max_length=8, null=True, verbose_name='ken furi')),
                ('city_name', models.CharField(blank=True, max_length=24, null=True, verbose_name='city name')),
                ('city_furi', models.CharField(blank=True, max_length=24, null=True, verbose_name='city furi')),
                ('town_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='town name')),
                ('town_furi', models.CharField(blank=True, max_length=32, null=True, verbose_name='town furi')),
                ('town_memo', models.CharField(blank=True, max_length=16, null=True, verbose_name='town memo')),
                ('kyoto_street', models.CharField(blank=True, max_length=32, null=True, verbose_name='kyoto street')),
                ('block_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='block name')),
                ('block_furi', models.CharField(blank=True, max_length=64, null=True, verbose_name='block furi')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='memo')),
                ('office_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='office name')),
                ('office_furi', models.CharField(blank=True, max_length=255, null=True, verbose_name='office furi')),
                ('office_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='office address')),
                ('new_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='new id')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='is deleted')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='updated date')),
            ],
            options={
                'verbose_name': 'postal code',
                'verbose_name_plural': 'postal codes',
            },
        ),
        migrations.RunPython(load_data_from_sql),
    ]
